/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Santé du système.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro_calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Calendar
         * @description Calendrier macro avec zones de blackout. Lit data/macro_calendar.json.
         */
        get: operations["get_macro_calendar_api_macro_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Status
         * @description État de l'horloge NYSE côté Alpaca (is_open, next_open, next_close).
         *
         *     Utilisé par le frontend pour désactiver Execute hors heures et par le broker
         *     comme fail-closed gate. Si Alpaca injoignable, retourne is_open=None (le
         *     frontend affiche un warning neutre plutôt que bloquer).
         */
        get: operations["get_market_status_api_market_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro
         * @description Régime macro-économique depuis macro_state.json.
         */
        get: operations["get_macro_api_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Journal CSV complet + equity state + positions ouvertes.
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equity_curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Equity Curve
         * @description Courbe d'équité calculée depuis le journal des trades clôturés.
         */
        get: operations["get_equity_curve_api_equity_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance_metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Performance Metrics
         * @description Agrégats PnL réalisés + ratios (Sharpe/Sortino/Calmar/DD/Expectancy).
         */
        get: operations["get_performance_metrics_api_performance_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Recommendations
         * @description Plan d'achat recommandé — top `max_holdings` actions en tendance haussière
         *     pondérées en risk parity (inverse-vol) sur le capital fourni.
         *
         *     Pipeline :
         *       1. Charge les tickers scorés (cache mtime-keyed de sector_metrics).
         *       2. Filtre bullish (momentum 6M > 0).
         *       3. Top N par titan_composite_score.
         *       4. Poids W_i = (1/σ_i) / Σ(1/σ_j) via volatilité 6M (Polygon/yf).
         *       5. Montants $ + shares (entières sauf allow_fractional_shares=true).
         *
         *     Query params :
         *       total_capital            : float, capital total à allouer (défaut 100k).
         *       max_holdings             : int, concentration (défaut 20).
         *       allow_fractional_shares  : bool, actions fractionnelles (défaut false).
         *       sector                   : str, restreint l'univers à un secteur GICS.
         *
         *     Réponse : {allocations: {TICKER: {weight_pct, amount_usd, shares,
         *               titan_score, momentum_pct, volatility_pct, imputed_vol, ...}},
         *               invested_usd, cash_remaining_usd, n_kept, ...}.
         *
         *     Cas des volatilités manquantes (< 60 bars d'historique) :
         *       - ≥ 3 tickers avec σ valide → imputation médiane cross-portfolio,
         *         flag imputed_vol=true sur les tickers concernés.
         *       - < 3 valid → equal_weight_fallback=true (signal insuffisant pour RP).
         */
        get: operations["get_portfolio_recommendations_api_portfolio_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Quantamental Universe
         * @description Rafraîchit l'univers quantamental en subprocess détaché.
         *
         *     Deux modes (mode="staggered" par défaut) :
         *       • staggered → universe_scheduler : budget 50 tickers/jour, skip ceux
         *         refreshés < 14j, merge non-destructif. **Quota-friendly** (~150 calls
         *         FMP sur 250/j disponibles). Mode recommandé pour les usages réguliers.
         *       • full → universe_engine : rebuild intégral (~500 tickers × 3 calls =
         *         1500 calls FMP). Crame le quota journalier → **à réserver aux
         *         urgences** (corruption universe.json, nouveau déploiement).
         *
         *     Téléchargement lourd → renvoie immédiatement {job_id} pour polling
         *     via GET /api/jobs/{job_id}. Refuse (409) si un job est déjà en cours.
         */
        post: operations["rebuild_quantamental_universe_api_universe_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quantamental Universe
         * @description SOURCE OF TRUTH — univers quantamental long-terme.
         *     Lit data/universe.json. Payload : tickers enrichis (sector, market_cap,
         *     forward_pe, price targets, recommandations analystes), agrégation
         *     sectorielle, stats du dernier rebuild.
         *
         *     Filtre optionnel ?sector=Technology pour restreindre la réponse.
         *
         *     Conditional GET : émet un ETag basé sur la mtime de universe.json. Le
         *     client peut renvoyer `If-None-Match` → 304 Not Modified (zéro payload)
         *     tant que le rebuild n'a pas tourné. Le filtre `sector` est inclus dans
         *     l'ETag car il change la réponse.
         *
         *     Métadonnées W8 :
         *       - last_updated_timestamp / stale_days / is_stale : âge du cache
         *       - is_incomplete par ticker (flag injecté dans chaque entrée)
         *       - incomplete_count / incomplete_ratio : agrégat global
         */
        get: operations["get_quantamental_universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sectors
         * @description Liste des 11 secteurs GICS enrichis :
         *       • Agrégats robustes (médianes/std) depuis universe.json
         *       • Distribution des recommandations analystes
         *       • Top-3 tickers par upside et market cap
         *       • Momentum 6M via ETF sectoriel SPDR (cache 24h)
         *       • Rotation Score = 0.4·valuation + 0.3·sentiment + 0.3·upside
         *         (composantes normalisées min-max cross-sector, scaled 0-100)
         *
         *     Query params :
         *       refresh_momentum=true  → force re-download yfinance (bypass cache).
         *                                Requiert Authorization: Bearer (anti-ban IP).
         */
        get: operations["get_sectors_api_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors/{sector}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Detail
         * @description Détail d'un secteur : stats agrégées + tous ses tickers enrichis
         *     (upside_pct, reco_bucket) pour un rendu direct dans la vue drill-down.
         */
        get: operations["get_sector_detail_api_sectors__sector__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kill Job
         * @description Envoie SIGTERM au groupe de process du job puis reap si zombie.
         */
        post: operations["kill_job_api_job__job_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Trade
         * @description Ajoute un trade manuel dans le journal CSV.
         */
        post: operations["add_trade_api_trade_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Trade
         * @description Clôture la dernière position OPEN d'un ticker.
         */
        post: operations["close_trade_api_trade_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description Liste les propositions + meta du dernier refresh.
         *
         *     Effectue un sweep `expire_pending()` à chaque appel pour que l'UI voie les
         *     expirations en temps réel sans dépendre d'un cron séparé.
         *
         *     `last_refresh` expose l'audit du dernier run auto_proposer (gates +
         *     diagnostics + ran_at) sans forcer un nouveau refresh. Utile pour que
         *     l'UI affiche les gates rouges dès l'ouverture de la page.
         */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Proposals
         * @description Run le proposer (gates → allocation → top-N candidats) + enqueue les
         *     propositions retenues.
         *
         *     Réponse :
         *       - `result.gates` : audit complet (toutes gates, ok/ko + détail).
         *       - `result.proposals` : ce qui a effectivement été ajouté à la file.
         *       - `result.diagnostics` : sélection, portfolio, allocation summary.
         */
        post: operations["refresh_proposals_api_proposals_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Proposal
         * @description Approuve la proposition + ouvre le trade dans le journal.
         *
         *     Flow atomique :
         *       1. Marque la proposition `approved` (transition pending → approved).
         *       2. Écrit la ligne OPEN dans trade_journal.csv sous FileLock.
         *       3. Marque la proposition `executed` avec l'order_id généré.
         *
         *     Si l'écriture journal échoue après l'approbation, on tente de revert via
         *     une nouvelle proposition mais c'est best-effort — on log et on retourne 500.
         */
        post: operations["approve_proposal_api_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Proposal
         * @description Veto utilisateur — la proposition passe en `rejected`.
         */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Proposals
         * @description Purge les propositions pending puis relance le proposer.
         *
         *     Différence avec `/refresh` : on force-expire les pending existants AVANT
         *     le nouveau run. Permet à l'utilisateur de changer les paramètres (capital,
         *     mode, include_held) et obtenir un plan cohérent avec ces paramètres, sans
         *     être bloqué par le dédup intra-file (un ticker pending existant empêche
         *     sa re-proposition).
         *
         *     On passe par `expired` (pas `rejected`) pour ne PAS déclencher le cooldown
         *     veto 7 j. Les rejected existants ne sont pas touchés — leur cooldown
         *     reste actif (protège contre annuler un veto par mégarde).
         *
         *     Réponse : même shape que `/refresh` + `n_expired` dans diagnostics.
         */
        post: operations["regenerate_proposals_api_proposals_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/approve_batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Proposals Batch
         * @description Bulk-approve avec overrides par proposition.
         *
         *     Flow par item :
         *       1. Lookup proposition (404 si absente, 400 si pas pending).
         *       2. Applique les overrides (entry/sl/tp/size édités par l'UI).
         *       3. Valide SL < Entry < TP etc.
         *       4. Idempotence : intra-batch duplicate, déjà OPEN sans allow_top_up.
         *       5. Refuse si sector_exposure.over_cap=True sans ack_sector_warning.
         *       6. Live-price realignement (seuil 0.5%) pour aligner sur la source
         *          tracker → pas de glissement PnL à l'ouverture.
         *       7. broker.submit_order — si broker rejet, la proposition reste pending
         *          avec rejection_reason=last_broker_error (retry possible).
         *       8. Succès → transition pending → approved → executed + order_id.
         *
         *     Chaque item est indépendant — une erreur n'annule pas les autres.
         */
        post: operations["approve_proposals_batch_api_proposals_approve_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/reject_batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Proposals Batch
         * @description Veto en masse — chaque item peut avoir une raison distincte.
         */
        post: operations["reject_proposals_batch_api_proposals_reject_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots Endpoint
         * @description Liste les dates de snapshots historiques disponibles (Lot 6 storage).
         *
         *     Endpoint public — l'UI l'utilise pour borner le date-picker du ticker
         *     detail aux dates effectivement disponibles.
         */
        get: operations["list_snapshots_endpoint_api_history_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/ticker/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticker History Endpoint
         * @description Retourne l'historique d'un ticker. Champs par défaut = les scores TITAN
         *     + momentum + price (pratique pour grapher la trajectoire score/prix).
         */
        get: operations["ticker_history_endpoint_api_history_ticker__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Health
         * @description État de santé des providers + cache fundamentals + universe.
         *
         *     Champs principaux :
         *       - severity_global : ok | warning | critical (calculé sur les composantes)
         *       - yf_breaker : tripped, age, cooldown, auto_reset_in
         *       - fundamentals_cache : n_cached, ages
         *       - universe : fields_missing par champ, fetched_at distribution, sources
         *       - fmp : quota_used / quota_max si dispo
         *
         *     Endpoint **public** — pas d'info sensible, just observability.
         */
        get: operations["get_data_health_api_data_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data_health/refresh_flagged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Flagged Tickers
         * @description Invalide le cache pour les tickers ayant un flag dq_sanitize= puis
         *     lance un refresh staggered ciblé (force=<liste>, min_age_days=0).
         *
         *     Use case : après avoir déployé un fix qualité data (recovery dividend_yield,
         *     nouveaux bounds, etc.), ce bouton permet de voir l'effet **maintenant**
         *     sans attendre le cron quotidien de 06:00 UTC.
         *
         *     Coût : N calls yfinance où N = nombre de tickers flaggés (typiquement
         *     < 50 après stabilisation, peut monter à 300+ après un changement de bounds).
         *     Le circuit breaker YF reste actif — si ça trip, le job s'arrête proprement.
         */
        post: operations["refresh_flagged_tickers_api_data_health_refresh_flagged_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTradeRequest */
        AddTradeRequest: {
            /** Ticker */
            ticker: string;
            /** Direction */
            direction: string;
            /** Entry */
            entry: number;
            /** Stop Loss */
            stop_loss: number;
            /** Take Profit */
            take_profit: number;
            /** Size */
            size: number;
            /**
             * Signal
             * @default MANUAL
             */
            signal: string;
            /**
             * Sector
             * @default
             */
            sector: string;
        };
        /**
         * ApproveBatchItem
         * @description Une ligne du bulk-approve — id proposition + overrides + ack.
         */
        ApproveBatchItem: {
            /** Id */
            id: string;
            overrides?: components["schemas"]["ApproveOverride"] | null;
            /**
             * Ack Sector Warning
             * @default false
             */
            ack_sector_warning: boolean;
            /**
             * Allow Top Up
             * @default false
             */
            allow_top_up: boolean;
        };
        /** ApproveBatchRequest */
        ApproveBatchRequest: {
            /** Items */
            items?: components["schemas"]["ApproveBatchItem"][];
        };
        /** ApproveBatchResponse */
        ApproveBatchResponse: {
            /** Ok */
            ok: boolean;
            /** N Requested */
            n_requested: number;
            /** N Executed */
            n_executed: number;
            /** N Failed */
            n_failed: number;
            /** Results */
            results: components["schemas"]["ApproveBatchResult"][];
        };
        /** ApproveBatchResult */
        ApproveBatchResult: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Order Id */
            order_id?: string | null;
        };
        /**
         * ApproveOverride
         * @description Overrides éditables par l'utilisateur avant l'exécution broker.
         */
        ApproveOverride: {
            /** Entry */
            entry?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Take Profit */
            take_profit?: number | null;
            /** Size */
            size?: number | null;
        };
        /** CloseTradeRequest */
        CloseTradeRequest: {
            /** Ticker */
            ticker: string;
            /** Exit Price */
            exit_price: number;
            /** Result */
            result: string;
        };
        /** EquityCurveResponse */
        EquityCurveResponse: {
            /** Curve */
            curve?: components["schemas"]["EquityPoint"][];
            /** Final Equity */
            final_equity: number;
            /** Initial Equity */
            initial_equity: number;
        } & {
            [key: string]: unknown;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Date */
            date: string;
            /** Ticker */
            ticker: string;
            /** Pnl */
            pnl: number;
            /** Equity */
            equity: number;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** EquityState */
        EquityState: {
            /** Starting Equity */
            starting_equity: number;
            /** Current Equity */
            current_equity: number;
            /**
             * Realized Pnl
             * @default 0
             */
            realized_pnl: number;
            /**
             * Unrealized Pnl
             * @default 0
             */
            unrealized_pnl: number;
            /** Date */
            date?: string | null;
            /** Last Update */
            last_update?: string | null;
            /** Open Positions */
            open_positions?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** GenericOkResponse */
        GenericOkResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobLaunchResponse */
        JobLaunchResponse: {
            /** Ok */
            ok: boolean;
            job: components["schemas"]["JobMeta"];
        } & {
            [key: string]: unknown;
        };
        /** JobMeta */
        JobMeta: {
            /** Job Id */
            job_id: string;
            /** Name */
            name: string;
            /** Cmd */
            cmd: string;
            /** Pid */
            pid: number;
            /** Started */
            started: string;
            /** Log Path */
            log_path?: string | null;
            /** Running */
            running?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** JobOutputResponse */
        JobOutputResponse: {
            /** Job Id */
            job_id: string;
            /** Running */
            running: boolean;
            /** Cmd */
            cmd?: string | null;
            /** Lines */
            lines?: string[];
        } & {
            [key: string]: unknown;
        };
        /** MacroCalendarEvent */
        MacroCalendarEvent: {
            /** Date */
            date: string;
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Days Delta */
            days_delta: number;
            /** Blackout */
            blackout: boolean;
            /** Upcoming */
            upcoming: boolean;
        } & {
            [key: string]: unknown;
        };
        /** MacroCalendarResponse */
        MacroCalendarResponse: {
            /** Today */
            today: string;
            /** In Blackout */
            in_blackout: boolean;
            next_event?: components["schemas"]["MacroCalendarEvent"] | null;
            /** Events */
            events?: components["schemas"]["MacroCalendarEvent"][];
        } & {
            [key: string]: unknown;
        };
        /** MacroResponse */
        MacroResponse: {
            /** Regime */
            regime: string;
            /** Vix */
            vix?: number | null;
            /** Sp500 */
            sp500?: number | null;
            /** Ema200 */
            ema200?: number | null;
            /** Sp500 Vs Ema200 Pct */
            sp500_vs_ema200_pct?: number | null;
            /** Allowed Directions */
            allowed_directions?: string[];
            /** Last Update */
            last_update?: string | null;
            /** Error */
            error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** PerformanceMetricsResponse */
        PerformanceMetricsResponse: {
            /** Capital */
            capital: number;
            /** Pnl Total */
            pnl_total: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Total Closed */
            total_closed: number;
            /** Win Rate */
            win_rate: number;
            /** Profit Factor */
            profit_factor: number;
            /** Open Count */
            open_count: number;
            /**
             * Sharpe
             * @default 0
             */
            sharpe: number;
            /**
             * Sortino
             * @default 0
             */
            sortino: number;
            /**
             * Calmar
             * @default 0
             */
            calmar: number;
            /**
             * Max Drawdown Pct
             * @default 0
             */
            max_drawdown_pct: number;
            /**
             * Avg Win
             * @default 0
             */
            avg_win: number;
            /**
             * Avg Loss
             * @default 0
             */
            avg_loss: number;
            /**
             * Expectancy
             * @default 0
             */
            expectancy: number;
            /**
             * Streak
             * @default 0
             */
            streak: number;
            /**
             * Avg Holding Days
             * @default 0
             */
            avg_holding_days: number;
            /** Equity By Date */
            equity_by_date?: unknown[][];
            /** Pnl Raw */
            pnl_raw?: number[];
            /** Pnl Series */
            pnl_series?: number[];
            /** Daily Pnl */
            daily_pnl?: {
                [key: string]: number;
            };
            /** Per Ticker Pnl */
            per_ticker_pnl?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        } & {
            [key: string]: unknown;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            equity: components["schemas"]["EquityState"];
            /** Journal */
            journal?: {
                [key: string]: unknown;
            }[];
            /** Open Positions */
            open_positions?: {
                [key: string]: unknown;
            }[];
            /** Closed Trades */
            closed_trades?: {
                [key: string]: unknown;
            }[];
            stats: components["schemas"]["PortfolioStats"];
        } & {
            [key: string]: unknown;
        };
        /** PortfolioStats */
        PortfolioStats: {
            /** Total Trades */
            total_trades: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Account Equity */
            account_equity: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * RefreshRequest
         * @description Override optionnel des defaults du proposer.
         */
        RefreshRequest: {
            /** Total Capital */
            total_capital?: number | null;
            /** Max Holdings */
            max_holdings?: number | null;
            /** Min Free Slots */
            min_free_slots?: number | null;
            /** Min Proposal Usd */
            min_proposal_usd?: number | null;
            /** Allowed Regimes */
            allowed_regimes?: string[] | null;
            /** Ttl Hours */
            ttl_hours?: number | null;
            /**
             * Notify Telegram
             * @default true
             */
            notify_telegram: boolean;
            /** Allow Fractional Shares */
            allow_fractional_shares?: boolean | null;
            /** Include Held */
            include_held?: boolean | null;
            /** Top N Mode */
            top_n_mode?: string | null;
        };
        /** RejectBatchItem */
        RejectBatchItem: {
            /** Id */
            id: string;
            /**
             * Reason
             * @default user_veto
             */
            reason: string;
        };
        /** RejectBatchRequest */
        RejectBatchRequest: {
            /** Items */
            items?: components["schemas"]["RejectBatchItem"][];
        };
        /** RejectBatchResponse */
        RejectBatchResponse: {
            /** Ok */
            ok: boolean;
            /** N Requested */
            n_requested: number;
            /** N Rejected */
            n_rejected: number;
            /** N Failed */
            n_failed: number;
            /** Results */
            results: components["schemas"]["RejectBatchResult"][];
        };
        /** RejectBatchResult */
        RejectBatchResult: {
            /** Id */
            id: string;
            /** Ticker */
            ticker?: string | null;
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /**
             * Reason
             * @default user_veto
             */
            reason: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Ok */
            ok: boolean;
            /** Timestamp */
            timestamp: string;
            /** Trading Blocked */
            trading_blocked: boolean;
            /** Nuclear Stop */
            nuclear_stop: boolean;
            /** Open Positions */
            open_positions: number;
            /** Max Positions */
            max_positions: number;
            /** Daily Drawdown Pct */
            daily_drawdown_pct: number;
            /** Account Equity */
            account_equity: number;
            /** Regime */
            regime: string;
            /** Vix */
            vix?: number | null;
            /** Broker Mode */
            broker_mode: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * UniverseRebuildRequest
         * @description Payload optionnel pour POST /api/universe/rebuild.
         */
        UniverseRebuildRequest: {
            /** Indices */
            indices?: string[] | null;
            /** Min Market Cap */
            min_market_cap?: number | null;
            /** Workers */
            workers?: number | null;
            /** Max Retries */
            max_retries?: number | null;
            /** Timeout */
            timeout?: number | null;
            /** Mode */
            mode?: string | null;
            /** Budget */
            budget?: number | null;
            /** Min Age Days */
            min_age_days?: number | null;
            /** Force */
            force?: string[] | null;
        };
        /** UniverseResponse */
        UniverseResponse: {
            /** Version */
            version?: number | null;
            /** Updated At */
            updated_at?: string | null;
            /** Last Updated Timestamp */
            last_updated_timestamp?: number | null;
            /** Stale Days */
            stale_days?: number | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /**
             * Staleness Threshold Days
             * @default 7
             */
            staleness_threshold_days: number;
            /**
             * Incomplete Count
             * @default 0
             */
            incomplete_count: number;
            /**
             * Incomplete Ratio
             * @default 0
             */
            incomplete_ratio: number;
            /** Source Indices */
            source_indices?: string[];
            /** Filter */
            filter?: {
                [key: string]: unknown;
            };
            /** Stats */
            stats?: {
                [key: string]: unknown;
            };
            /** Sectors */
            sectors?: {
                [key: string]: unknown;
            };
            /** Tickers */
            tickers?: {
                [key: string]: unknown;
            };
            /** Count */
            count: number;
            /** Rebuilding */
            rebuilding: boolean;
            /** Rebuild Job Id */
            rebuild_job_id?: string | null;
            /** Last Change */
            last_change?: unknown;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_macro_calendar_api_macro_calendar_get: {
        parameters: {
            query?: {
                horizon_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroCalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_status_api_market_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_macro_api_macro_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroResponse"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    get_equity_curve_api_equity_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityCurveResponse"];
                };
            };
        };
    };
    get_performance_metrics_api_performance_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceMetricsResponse"];
                };
            };
        };
    };
    get_portfolio_recommendations_api_portfolio_recommendations_get: {
        parameters: {
            query?: {
                total_capital?: number;
                max_holdings?: number;
                allow_fractional_shares?: boolean;
                sector?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_quantamental_universe_api_universe_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UniverseRebuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quantamental_universe_api_universe_get: {
        parameters: {
            query?: {
                sector?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sectors_api_sectors_get: {
        parameters: {
            query?: {
                refresh_momentum?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_detail_api_sectors__sector__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOutputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_job_api_job__job_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_trade_api_trade_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_trade_api_trade_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseTradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                /** @description pending|approved|rejected|expired|executed */
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_proposals_api_proposals_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_proposals_api_proposals_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposals_batch_api_proposals_approve_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposals_batch_api_proposals_reject_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_endpoint_api_history_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ticker_history_endpoint_api_history_ticker__ticker__get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD */
                start?: string | null;
                end?: string | null;
                /** @description CSV des champs à extraire (default = scores TITAN principaux) */
                fields?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_health_api_data_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_flagged_tickers_api_data_health_refresh_flagged_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
